---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  data_path: test/shared
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: debian-7.8.0-amd64
  driver_config:
    box: debian-7.8.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/boxes/debian-7.8.0-amd64/versions/1.0.9/providers/virtualbox.box

suites:
- name: default
  run_list:
    - recipe[chef-handler-scrutinizer::default]
  attributes: {}